### Registro de nuevo usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "oscar@gmail.com",
    "password": "12345678910"
}

###Iniciar sesión con usuario registrado
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "userdemo@ejemplo.com",
    "password": "$2b$10$/WmVzuaTz3BkJU1.RKEfX.p2OZB8tOYPTcgoTzLv6fftZFdjqgHa6"
}

###Obtener la lista de usuarios
GET http://localhost:3000/api/users

###Obtener usuario por ID
GET http://localhost:3000/api/users/67dad09d7253bfb065eff01b

###Actualizar datos de un usuario
PUT http://localhost:3000/api/users/67dad09d7253bfb065eff01b
Content-Type: application/json

{
    "name": "Juan",
    "lastname": "Fernandez",
    "nif": "12345678X"
}

###Eliminar usuario por ID
DELETE http://localhost:3000/api/users/67dad0d7253bfb065eff01b


###Validar el email con código
POST http://localhost:3000/api/auth/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGJiODIyYzQ5YzdiNWVmMDY0YmIyNyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQyNDUyNzcwLCJleHAiOjE3NDI0NTk5NzB9.9YFps5suauCv-FfiE05-eMWAfhSWUGSba3TJFpzZILw

{
    "code": "505683"
}
###Enviar email
POST http://localhost:3000/api/email/send
Content-Type: application/json

{
    "subject": "Prueba de correo",
    "text": "Este correo solo llegará a gente con calvicie severa.",
    "to": "oscarcorrochanolopez@gmail.com",
    "from": "oscarcorrochanolopez@gmail.com"
}